version: '3'
services:
  psql:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES="bookstore","bookstore-test"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
